/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

//! Thin wrapper around zstd's dictionary mode that we use to build/apply deltas
//! when git offset deltas alone are not enough.

use std::{cmp, io};

use zstd::{
    bulk::{Compressor, Decompressor},
    zstd_safe::{self, CParameter, Strategy},
};

const ZSTD_WINDOWLOG_MAX: u32 = 30;
const ZSTD_HASHLOG_MAX: u32 = 30;

fn log_base2(x: u64) -> u32 {
    64 - x.leading_zeros()
}

fn clamp(v: u32, min: u32, max: u32) -> u32 {
    cmp::max(min, cmp::min(v, max))
}

/// Create a "zstd delta". Compress `data` using dictionary `base`.
pub fn diff(base: &[u8], data: &[u8]) -> io::Result<Vec<u8>> {
    let mut compressor = Compressor::with_dictionary(1, base)?;
    let log = log_base2((data.len() + base.len() + 1) as u64);
    compressor.set_parameter(CParameter::WindowLog(clamp(
        log,
        zstd_safe::WINDOWLOG_MIN,
        ZSTD_WINDOWLOG_MAX,
    )))?;
    compressor.set_parameter(CParameter::HashLog(clamp(
        log,
        zstd_safe::HASHLOG_MIN,
        ZSTD_HASHLOG_MAX,
    )))?;
    compressor.set_parameter(CParameter::SearchLog(zstd_safe::SEARCHLOG_MIN))?;
    compressor.set_parameter(CParameter::MinMatch(7))?;
    compressor.set_parameter(CParameter::TargetLength(0))?;
    compressor.set_parameter(CParameter::Strategy(Strategy::ZSTD_fast))?;
    compressor.compress(data)
}

/// Apply a zstd `delta` generated by `diff` to `base`. Return reconstructed `data`.
pub fn apply(base: &[u8], delta: &[u8]) -> io::Result<Vec<u8>> {
    let mut decompressor = Decompressor::with_dictionary(base)?;
    decompressor.decompress(delta, usize::MAX)
}

#[cfg(test)]
mod tests {
    use chacha20::ChaCha20Rng;
    use quickcheck::quickcheck;
    use rand::{Rng, SeedableRng};

    use super::*;

    /// Helper: diff/apply round-trip for a given base/data pair.
    fn check_round_trip(base: &[u8], data: &[u8]) -> bool {
        let delta = diff(base, data).expect("delta");
        let reconstructed = apply(base, &delta).expect("apply");
        reconstructed[..] == data[..]
    }

    /// Deterministic round-trip cases (empty, shrink, grow) to ensure zstd delta apply works.
    #[test]
    fn test_round_trip_manual() {
        assert!(check_round_trip(b"", b""));
        assert!(check_round_trip(b"123", b""));
        assert!(check_round_trip(b"", b"123"));
        assert!(check_round_trip(b"1234567890", b"3"));
        assert!(check_round_trip(b"3", b"1234567890"));
    }

    /// Efficiency smoke test: random 1MB base with few byte flips should produce a small delta.
    #[test]
    fn test_delta_efficiency() {
        // 1 MB incompressible random data
        let mut base = vec![0u8; 1000000];
        let mut rng = ChaCha20Rng::from_seed([0; 32]);
        rng.fill_bytes(&mut base);
        // Change a few bytes
        let mut data = base.clone();
        data[0] ^= 1;
        data[10000] ^= 3;
        data[900000] ^= 7;
        let delta = diff(&base, &data).expect("diff");
        // Should generate a small delta.
        // Note: this will fail if wlog/hlog are not tweaked.
        assert!(delta.len() < 200);
    }

    quickcheck! {
        /// Property test: for arbitrary inputs, diff/apply should round-trip.
        fn test_round_trip_quickcheck(a: Vec<u8>, b: Vec<u8>) -> bool {
            check_round_trip(&a, &b)
        }
    }
}
